### ISSUE TITLE
fixed menu

### ISSUE THREAD

**Issue by lucabassplayer89** [BlackrockDigital/startbootstrap-sb-admin#96] opened 2019-02-14 11:48 UTC
is it possible to have the sidebar on the left and on the top fixed?

**Comment by davidtmiller** [comment] 2019-05-08 19:55
It's something I've played with in the past and I may add functionality into the CSS for this in the future at some point.

**Comment by davidtmiller** [comment] 2019-05-08 19:57
Duplicate of #85

**Closed by davidtmiller** 2019-05-08 19:57 UTC
Labels: duplicate
